import Logo from "./logo.svg"
import HeroImg from "./hero-img.png"
import CupCake from "./cupcake.svg"
import Pizza from "./pizza.svg"
import Kebab from "./kebab.svg"
import Salmon from "./salmon.svg"
import Doughnut from "./doughnut.svg"
import PizzaPaperoni from "./paperoni.svg"
import PizzaMeat from "./meat.svg"
import DonerKebab from "./donerkebab.svg"
import SalmonRoll from "./salmonroll.svg"
import CupcakeChoco from "./cupcakechoco.svg"
import DoughnutMilk from "./doughnutmilk.svg"
import DoughnutUnicorn from "./doughnutunicorn.svg"
import KathiKebab from "./kathikebab.svg"
import Rating from "./rating.svg"
import BgImg from "./background.svg"

export { Logo, HeroImg, CupCake, Pizza, Kebab, Salmon, Doughnut, PizzaPaperoni, PizzaMeat, DonerKebab, SalmonRoll, CupcakeChoco, DoughnutMilk, DoughnutUnicorn, KathiKebab, Rating,BgImg }